(()=>{
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
const memoryFallback=new Map();let storageAvailable=true;const db={get(k,d){try{const saved=localStorage.getItem('hoa_v2_'+k);if(saved!==null)return JSON.parse(saved)}catch{storageAvailable=false}return memoryFallback.has(k)?memoryFallback.get(k):d},set(k,v){memoryFallback.set(k,v);try{localStorage.setItem('hoa_v2_'+k,JSON.stringify(v));storageAvailable=true;return true}catch{storageAvailable=false;return false}}};
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let orders=db.get('orders',[]);
let automations=db.get('automations',[{name:'Recepción inteligente',desc:'Registra solicitudes y prepara una orden de trabajo.',icon:'ti-inbox',on:false},{name:'Diagnóstico de frenos',desc:'Lista de verificación según tren motriz y síntomas.',icon:'ti-activity',on:false},{name:'Recordatorio de mantenimiento',desc:'Avisa al cliente cuando se acerca su próxima inspección.',icon:'ti-calendar-repeat',on:false},{name:'Alerta de inventario',desc:'Notifica cuando los repuestos bajan del mínimo.',icon:'ti-package',on:false},{name:'Informe diario J.A.R.V.I.S.',desc:'Resumen de órdenes y cobros al cierre del día.',icon:'ti-report-analytics',on:false},{name:'Sincronización con hoja',desc:'Sincroniza movimientos de caja con Google Sheets.',icon:'ti-brand-google-drive',on:false}]);
let vehicles=db.get('vehicles',[]);
let inventory=db.get('inventory',[]);
let notices=db.get('notices',[]);
let tickets=db.get('tickets',[]),messages=db.get('messages',[]),ledger=db.get('ledger',[]);
const keyMap=['intake','brake_diagnosis','maintenance_reminders','inventory_alerts','daily_report','sheets_sync'];
function persist(){let saved=true;for(const [k,v] of Object.entries({orders,automations,vehicles,inventory,notices,tickets,messages,ledger}))saved=db.set(k,v)&&saved;if(!saved)toast('El navegador bloqueó el guardado permanente. Abre el sitio con HTTPS o desde localhost y habilita el almacenamiento.')}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;$('#toasts')?.append(el);setTimeout(()=>el.remove(),3400)}
const api=async(action,options={})=>{const r=await fetch(`../api/index.php?action=${encodeURIComponent(action)}`,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json();if(!r.ok){const err=new Error(data.error||'Error de servidor');err.status=r.status;throw err}return data};
function sheetsConfig(){return db.get('sheetConfig',{spreadsheetUrl:db.get('sheetUrl',''),webAppUrl:'',token:''})}
function setSheetsStatus(text){const el=$('#sheets-status');if(el)el.textContent=text}
function sheetRows(){let balance=0;return [...ledger].sort((a,b)=>String(a.date).localeCompare(String(b.date))||Number(a.id||0)-Number(b.id||0)).map(m=>{balance+=Number(m.income||0)-Number(m.expense||0);return{id:String(m.id),date:String(m.date),reason:String(m.reason),income:Number(m.income||0),expense:Number(m.expense||0),balance}})}
function syncGoogleSheet(){const c=sheetsConfig();if(!c.spreadsheetUrl||!c.webAppUrl||!c.token) return Promise.reject(new Error('Completa el enlace de la hoja, la URL de Apps Script y el token.'));if(!/^https:\/\/docs\.google\.com\/spreadsheets\/d\/[\w-]+/.test(c.spreadsheetUrl))return Promise.reject(new Error('El enlace debe ser de una hoja de Google Sheets.'));if(!/^https:\/\/script\.google\.com\/macros\/s\/[\w-]+\/exec$/.test(c.webAppUrl))return Promise.reject(new Error('La URL de Apps Script debe terminar en /exec.'));const requestId=`hoa-${Date.now()}-${Math.random().toString(36).slice(2)}`,frame=document.createElement('iframe'),form=document.createElement('form'),payload=document.createElement('input');frame.name=requestId;frame.hidden=true;form.hidden=true;form.method='POST';form.target=requestId;form.action=c.webAppUrl;payload.type='hidden';payload.name='payload';payload.value=JSON.stringify({requestId,token:c.token,movements:sheetRows()});form.append(payload);document.body.append(frame,form);setSheetsStatus('Enviando movimientos a Google Sheets…');return new Promise((resolve,reject)=>{const finish=(err,result)=>{clearTimeout(timer);window.removeEventListener('message',onMessage);form.remove();frame.remove();err?reject(err):resolve(result)};const onMessage=e=>{if(e.source!==frame.contentWindow||e.data?.requestId!==requestId)return;if(!e.data.ok)finish(new Error(e.data.error||'Google Apps Script rechazó la sincronización.'));else finish(null,e.data)};window.addEventListener('message',onMessage);const timer=setTimeout(()=>finish(new Error('No llegó respuesta de Apps Script. Revisa el despliegue y vuelve a sincronizar.')),30000);try{form.submit()}catch(err){finish(err)}})}
async function loadBackend(){try{const data=await api('orders');const serverOrders=(data.orders||[]).map(o=>({...o,price:o.price?`Bs ${o.price}`:'Por cotizar',time:o.time?new Date(o.time).toLocaleTimeString('es-BO',{hour:'2-digit',minute:'2-digit'}):''}));const serverIds=new Set(serverOrders.map(o=>String(o.id)));orders=[...serverOrders,...orders.filter(o=>!serverIds.has(String(o.id)))];db.set('orders',orders)}catch{}try{const data=await api('automations');const states=new Map((data.automations||[]).map(a=>[a.key,!!Number(a.enabled)]));automations.forEach((a,i)=>{if(states.has(keyMap[i]))a.on=states.get(keyMap[i])});db.set('automations',automations)}catch{}try{const data=await api('cash-flow');const serverMovements=data.movements||[],serverIds=new Set(serverMovements.map(m=>String(m.id)));ledger=[...serverMovements,...ledger.filter(m=>!serverIds.has(String(m.id)))];db.set('ledger',ledger)}catch{}fillPage(document.body.dataset.page)}
const money=n=>`Bs ${Number(n||0).toLocaleString('es-BO',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const badge=s=>`<span class="status ${s==='En reparación'?'blue':s==='Esperando repuesto'?'amber':s==='En diagnóstico'?'amber':''}">${escapeHtml(s)}</span>`;
function orderRows(list){return list.map(o=>`<tr><td class="mono"><b>${escapeHtml(o.id)}</b><br><span style="color:#718397">${escapeHtml(o.client)}</span></td><td><div class="vehicle"><span class="vehicle-icon"><i class="ti ti-car"></i></span><span><b>${escapeHtml(o.vehicle)}</b><br><span style="color:#74869a">${escapeHtml(o.year)} · ${escapeHtml(o.type)}</span></span></div></td><td>${escapeHtml(o.service)}</td><td>${badge(o.status)}</td><td class="mono">${escapeHtml(o.time)}</td><td><button class="link-btn" data-action="cycle-order" data-id="${escapeHtml(o.id)}">Cambiar estado</button></td></tr>`).join('')}
function fillPage(page){
 const ordersBody=$('#orders-table');if(ordersBody){ordersBody.innerHTML=orders.length?orderRows(orders):'<tr><td colspan="6" class="empty-state">Aún no hay órdenes registradas.</td></tr>';$$('[data-count]').forEach(e=>e.textContent=orders.filter(o=>o.status===e.dataset.count).length)}
 const recent=$('#recent-orders');if(recent)recent.innerHTML=orders.length?orders.slice(0,3).map(o=>`<tr><td class="mono"><b>${escapeHtml(o.id)}</b></td><td><b>${escapeHtml(o.vehicle)}</b><br><span style="color:#74869a">${escapeHtml(o.client)}</span></td><td>${escapeHtml(o.service)}</td><td>${badge(o.status)}</td><td><a class="link-btn" href="ordenes-trabajo.html">Abrir</a></td></tr>`).join(''):'<tr><td colspan="5" class="empty-state">Aún no hay órdenes registradas.</td></tr>';
 const autos=$('#automation-list');if(autos)autos.innerHTML=automations.map((a,i)=>`<div class="automation-card"><span class="auto-icon"><i class="ti ${a.icon}"></i></span><div><b>${escapeHtml(a.name)}</b><p>${escapeHtml(a.desc)}</p></div><input class="switch" type="checkbox" data-auto="${i}" ${a.on?'checked':''} aria-label="${escapeHtml(a.name)}"></div>`).join('');
 const controls=$('#control-list');if(controls)controls.innerHTML=automations.slice(0,4).map((a,i)=>`<div class="automation-card"><span class="auto-icon"><i class="ti ${a.icon}"></i></span><div><b>${escapeHtml(a.name)}</b><p>${a.on?'Activa':'Pausada'}</p></div><input class="switch" type="checkbox" data-auto="${i}" ${a.on?'checked':''}></div>`).join('');
 const vbody=$('#vehicles-table');if(vbody)vbody.innerHTML=vehicles.length?vehicles.map(v=>`<tr><td><b>${escapeHtml(v.vehicle)}</b></td><td>${escapeHtml(v.client)}</td><td>${badge(v.type)}</td><td>${escapeHtml(v.service)}</td><td class="mono">${escapeHtml(v.next)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty-state">Aún no hay vehículos registrados.</td></tr>';
 const ibody=$('#inventory-table');if(ibody)ibody.innerHTML=inventory.length?inventory.map((item,i)=>`<tr><td><b>${escapeHtml(item.name)}</b></td><td>${escapeHtml(item.fit)}</td><td class="mono">${item.qty} un.</td><td class="mono">${item.min} un.</td><td>${item.qty<=item.min?'<span class="status red">Reponer</span>':'<span class="status">Disponible</span>'}</td><td><button class="link-btn" data-action="use-stock" data-index="${i}">Descontar 1</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty-state">Aún no hay repuestos registrados.</td></tr>';
 const nlist=$('#notifications-list');if(nlist)nlist.innerHTML=notices.length?notices.map(n=>`<div class="notice"><span class="notice-icon"><i class="ti ${n.icon}"></i></span><div><b>${escapeHtml(n.title)}</b><p>${escapeHtml(n.body)}</p><time>${escapeHtml(n.time)}</time></div></div>`).join(''):'<div class="empty-state">No tienes notificaciones pendientes.</div>';
 const tlist=$('#tickets-list');if(tlist)tlist.innerHTML=tickets.length?tickets.map(t=>`<div class="activity-row"><span class="activity-icon amber"><i class="ti ti-alert-circle"></i></span><div><b>${escapeHtml(t.title)}</b><p>${escapeHtml(t.detail)} · ${escapeHtml(t.time)}</p></div>${badge('En revisión')}</div>`).join(''):'<div class="empty-state">Todavía no hay solicitudes. Crea una para comenzar.</div>';
 const mlist=$('#chat-messages');if(mlist)mlist.innerHTML=messages.length?messages.map(m=>`<div class="message ${m.sender==='Taller'?'self':''}">${escapeHtml(m.text)}<small>${escapeHtml(m.sender)} · ${escapeHtml(m.time)}</small></div>`).join(''):'<div class="empty-state">No hay mensajes todavía.</div>';
 const ordered=[...ledger].sort((a,b)=>String(a.date).localeCompare(String(b.date))||Number(a.id||0)-Number(b.id||0));let balance=0;const rows=ordered.map(m=>{balance+=Number(m.income||0)-Number(m.expense||0);return {...m,balance}});const incomes=rows.reduce((s,m)=>s+Number(m.income||0),0),expenses=rows.reduce((s,m)=>s+Number(m.expense||0),0);
 const ledgerBody=$('#ledger-table');const cfg=sheetsConfig(),sheetUrlField=$('#sheet-form [name=\"url\"]'),scriptUrlField=$('#sheet-form [name=\"webAppUrl\"]'),tokenField=$('#sheet-form [name=\"token\"]');if(sheetUrlField&&document.activeElement!==sheetUrlField)sheetUrlField.value=cfg.spreadsheetUrl||'';if(scriptUrlField&&document.activeElement!==scriptUrlField)scriptUrlField.value=cfg.webAppUrl||'';if(tokenField&&document.activeElement!==tokenField)tokenField.value=cfg.token||'';setSheetsStatus(cfg.webAppUrl?'Conector configurado. Guarda o sincroniza para actualizar la hoja.':'Falta configurar el despliegue de Apps Script.');if(ledgerBody)ledgerBody.innerHTML=rows.length?rows.map(m=>`<tr><td>${escapeHtml(m.date)}</td><td>${escapeHtml(m.reason)}</td><td class="mono">${money(m.income)}</td><td class="mono">${money(m.expense)}</td><td class="mono">${money(m.balance)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty-state">Sin movimientos. El saldo inicial es Bs 0,00.</td></tr>';
 $$('[data-ledger-income]').forEach(e=>e.textContent=money(incomes));$$('[data-ledger-expense]').forEach(e=>e.textContent=money(expenses));$$('[data-ledger-balance]').forEach(e=>e.textContent=money(balance));
 $$('[data-stat="orders"]').forEach(e=>e.textContent=orders.filter(o=>!['Cerrada','Listo para entrega'].includes(o.status)).length);
 $$('[data-stat="vehicles"]').forEach(e=>e.textContent=vehicles.length);
 $$('[data-stat="automations"]').forEach(e=>e.textContent=automations.filter(a=>a.on).length);
 const n=$('[data-active-count]');if(n)n.textContent=`${automations.filter(a=>a.on).length} ACTIVAS`;
 const session=db.get('session',null);if(session){const a=$('#top-user'),b=$('#sidebar-user');if(a)a.textContent=session.name;if(b)b.textContent=session.name}
}
function openModal(html){const m=$('#modal');if(m){$('#modal-content').innerHTML=html;m.classList.add('open');m.setAttribute('aria-hidden','false')}}function closeModal(){$('#modal')?.classList.remove('open');$('#modal')?.setAttribute('aria-hidden','true')}
function orderForm(){openModal(`<div class="eyebrow">ORDEN DE TRABAJO</div><h2>Registrar vehículo</h2><p>La orden se guarda en este navegador o en el API MySQL si XAMPP está configurado.</p><form id="order-form"><div class="form-grid"><div class="field"><label>Cliente</label><input name="client" required placeholder="Nombre y apellido"></div><div class="field"><label>Vehículo</label><input name="vehicle" required placeholder="Marca y modelo"></div><div class="field"><label>Año</label><input name="year" type="number" min="1950" max="2100" required placeholder="2022"></div><div class="field"><label>Tren motriz</label><select name="type"><option>Convencional</option><option>Híbrido</option><option>Eléctrico</option></select></div><div class="field full"><label>Servicio / síntoma de frenos</label><input name="service" required placeholder="Ej. testigo ABS encendido"></div></div><button class="btn primary">Crear orden</button></form>`)}
function login(){openModal(`<div class="eyebrow">ACCESO ADMINISTRADOR</div><h2>Iniciar sesión</h2><p>Credenciales creadas en MySQL mediante la guía XAMPP.</p><form id="login-form"><div class="field"><label>Correo</label><input name="email" type="email" required></div><div class="field"><label>Contraseña</label><input name="password" type="password" required></div><button class="btn primary">Entrar</button></form>`)}
function bindForms(){
 const dateField=$('#cash-movement-form [name="date"]');if(dateField&&!dateField.value)dateField.value=new Date().toISOString().slice(0,10);
 $('#order-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));let item;try{const result=await api('orders',{method:'POST',body:JSON.stringify(f)});item={...f,id:result.id,status:'En diagnóstico',time:new Date().toLocaleTimeString('es-BO',{hour:'2-digit',minute:'2-digit'}),price:'Por cotizar'};toast('Orden guardada en MySQL.')}catch(err){if(err.status===401){closeModal();login();toast('Inicia sesión para guardar en el servidor.');return}item={...f,id:`HA-${Date.now().toString().slice(-6)}`,status:'En diagnóstico',time:new Date().toLocaleTimeString('es-BO',{hour:'2-digit',minute:'2-digit'}),price:'Por cotizar'};toast('Servidor no disponible: orden guardada localmente.')}orders.unshift(item);vehicles.unshift({vehicle:`${f.vehicle} ${f.year}`,client:f.client,type:f.type,service:f.service,next:'Por programar'});notices.unshift({title:`Nueva orden ${item.id}`,body:`${f.client} · ${f.vehicle}`,time:'Ahora',icon:'ti-clipboard-list'});persist();closeModal();fillPage(document.body.dataset.page)});
 $('#login-form')?.addEventListener('submit',async e=>{e.preventDefault();try{const result=await api('login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});db.set('session',{name:result.name});closeModal();fillPage(document.body.dataset.page);await loadBackend();toast('Sesión iniciada.')}catch(err){toast(err.message)}});
 $('#vehicle-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));vehicles.unshift({...f,vehicle:f.vehicle,client:f.client,type:f.type,service:'Sin servicios registrados',next:'Por programar'});persist();closeModal();fillPage(document.body.dataset.page);toast('Vehículo guardado.')});
 $('#inventory-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));inventory.unshift({name:f.name,fit:f.fit,qty:Number(f.qty),min:Number(f.min)});persist();closeModal();fillPage(document.body.dataset.page);toast('Pieza registrada.')});
 $('#ticket-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));tickets.unshift({...f,time:'Ahora'});persist();closeModal();fillPage(document.body.dataset.page);toast('Solicitud de soporte registrada.')});
 $('#chat-form')?.addEventListener('submit',e=>{e.preventDefault();const field=$('#chat-input'),text=field.value.trim();if(!text)return;messages.push({text,sender:'Taller',time:'Ahora'});persist();fillPage(document.body.dataset.page)});
 $('#cash-movement-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),amount=Number(f.amount);if(!Number.isFinite(amount)||amount<=0){toast('Ingresa un importe mayor que cero.');return}const item={date:f.date,reason:f.reason.trim(),income:f.type==='ingreso'?amount:0,expense:f.type==='egreso'?amount:0};try{const result=await api('cash-flow',{method:'POST',body:JSON.stringify(item)});item.id=result.id;toast('Movimiento guardado en MySQL.')}catch(err){if(err.status===401){login();bindForms();toast('Inicia sesión para guardar en MySQL.');return}item.id=Date.now();toast('Servidor no disponible: movimiento guardado en este navegador.')}ledger.push(item);persist();e.currentTarget.reset();fillPage(document.body.dataset.page);if(sheetsConfig().webAppUrl){try{const result=await syncGoogleSheet();setSheetsStatus('Sincronizado: '+result.synced+' movimientos.');toast('Caja sincronizada con Google Sheets.')}catch(err){setSheetsStatus('Error de sincronización: '+err.message);toast('Se guardó en la caja, pero Sheets no se actualizó: '+err.message)}}});
}
function vehicleForm(){openModal(`<div class="eyebrow">FICHA DEL CLIENTE</div><h2>Añadir vehículo</h2><form id="vehicle-form"><div class="field"><label>Propietario</label><input name="client" required placeholder="Nombre del cliente"></div><div class="field"><label>Marca, modelo y año</label><input name="vehicle" required placeholder="Toyota Prius 2021"></div><div class="field"><label>Tren motriz</label><select name="type"><option>Híbrido</option><option>Eléctrico</option><option>Convencional</option></select></div><button class="btn primary">Guardar ficha</button></form>`);bindForms()}
function inventoryForm(){openModal(`<div class="eyebrow">INVENTARIO</div><h2>Registrar repuesto</h2><form id="inventory-form"><div class="field"><label>Nombre de pieza</label><input name="name" required></div><div class="field"><label>Compatibilidad</label><input name="fit" required></div><div class="form-grid"><div class="field"><label>Stock actual</label><input name="qty" type="number" min="0" value="0"></div><div class="field"><label>Mínimo</label><input name="min" type="number" min="0" value="1"></div></div><button class="btn primary">Guardar pieza</button></form>`);bindForms()}
function ticketForm(){openModal(`<div class="eyebrow">SOPORTE</div><h2>Nueva solicitud</h2><form id="ticket-form"><div class="field"><label>Asunto</label><input name="title" required placeholder="Describe el problema"></div><div class="field"><label>Detalle</label><textarea name="detail" required rows="4"></textarea></div><button class="btn primary">Enviar solicitud</button></form>`);bindForms()}
window.addEventListener('hall:ready',e=>{fillPage(e.detail.page);bindForms();$('#mobile-menu')?.addEventListener('click',()=>$('.sidebar')?.classList.toggle('open'));if(db.get('session',null))loadBackend()});
window.addEventListener('storage',e=>{if(!e.key?.startsWith('hoa_v2_'))return;const key=e.key.slice('hoa_v2_'.length);try{const value=JSON.parse(e.newValue);memoryFallback.set(key,value);if(key==='orders')orders=value;else if(key==='automations')automations=value;else if(key==='vehicles')vehicles=value;else if(key==='inventory')inventory=value;else if(key==='notices')notices=value;else if(key==='tickets')tickets=value;else if(key==='messages')messages=value;else if(key==='ledger')ledger=value;fillPage(document.body.dataset.page)}catch{}});
document.addEventListener('click',async e=>{
 const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;
 if(action==='close-modal'){closeModal();return}if(action==='login'){login();bindForms();return}if(action==='new-order'){orderForm();bindForms();return}if(action==='new-vehicle'){vehicleForm();return}if(action==='add-stock'){inventoryForm();return}if(action==='new-ticket'){ticketForm();return}
 if(action==='read-all'){notices=[];persist();fillPage(document.body.dataset.page);toast('Notificaciones marcadas como leídas.');return}
 if(action==='sheets-sync'){try{const result=await syncGoogleSheet();setSheetsStatus('Conectado. '+result.synced+' movimientos sincronizados.');toast('Google Sheets actualizado correctamente.')}catch(err){setSheetsStatus('Error de sincronización: '+err.message);toast(err.message)}return}
 if(action==='open-sheet'){const url=sheetsConfig().spreadsheetUrl||db.get('sheetUrl','');if(url.startsWith('https://docs.google.com/spreadsheets/'))window.open(url,'_blank','noopener');else toast('Guarda primero una URL válida de Google Sheets.');return}
 if(action==='add-ledger'){document.querySelector('#cash-movement-form [name="date"]')?.focus();return}
 if(action==='ledger-export'){const rows=[['Fecha','Motivo','Ingresos','Egresos','Saldo']];let total=0;[...ledger].sort((a,b)=>String(a.date).localeCompare(String(b.date))||Number(a.id||0)-Number(b.id||0)).forEach(m=>{total+=Number(m.income||0)-Number(m.expense||0);rows.push([m.date,m.reason,m.income||0,m.expense||0,total.toFixed(2)])});const csv='\ufeff'+rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(';')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='hall-of-armor-caja.csv';a.click();URL.revokeObjectURL(url);return}
 if(action==='refresh'){toast('Estado local actualizado.');return}
 if(action==='export'){const blob=new Blob([JSON.stringify(orders,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hall-of-armor-ordenes.json';a.click();URL.revokeObjectURL(url);toast('Resumen descargado.');return}
 if(action==='cycle-order'){const o=orders.find(x=>x.id===e.target.closest('[data-id]').dataset.id);if(!o)return;const states=['En diagnóstico','En reparación','Esperando repuesto','Listo para entrega','Cerrada'];o.status=states[(states.indexOf(o.status)+1)%states.length];persist();try{await api('orders',{method:'PATCH',body:JSON.stringify({id:o.id,status:o.status})})}catch{}fillPage(document.body.dataset.page);toast(`${o.id}: ${o.status}`);return}
 if(action==='use-stock'){const index=Number(e.target.closest('[data-index]').dataset.index);if(inventory[index].qty>0)inventory[index].qty--;persist();fillPage(document.body.dataset.page);toast(`Stock actualizado: ${inventory[index].name}`)}
});
document.addEventListener('change',async e=>{if(!e.target.matches('[data-auto]'))return;const i=Number(e.target.dataset.auto);automations[i].on=e.target.checked;persist();try{await api('automations',{method:'PATCH',body:JSON.stringify({key:keyMap[i],enabled:e.target.checked})})}catch{}fillPage(document.body.dataset.page);toast(`${automations[i].name} ${e.target.checked?'activada':'pausada'}.`)});
document.addEventListener('submit',async e=>{if(e.target.id==='sheet-form'){e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),config={spreadsheetUrl:(f.url||'').trim(),webAppUrl:(f.webAppUrl||'').trim(),token:(f.token||'').trim()};if(config.spreadsheetUrl&&!/^https:\/\/docs\.google\.com\/spreadsheets\/d\/[\w-]+/.test(config.spreadsheetUrl)){toast('Pega un enlace válido de Google Sheets.');return}db.set('sheetConfig',config);db.set('sheetUrl',config.spreadsheetUrl);if(!config.webAppUrl||!config.token){setSheetsStatus('Enlace guardado. Completa Apps Script y el token para activar la sincronización.');toast('Enlace guardado. Falta configurar Apps Script y el token.');return}try{const result=await syncGoogleSheet();setSheetsStatus('Conectado. '+result.synced+' movimientos sincronizados.');toast('Google Sheets actualizado correctamente.')}catch(err){setSheetsStatus('No se pudo sincronizar: '+err.message);toast('No se pudo actualizar Google Sheets: '+err.message)}}else if(e.target.id==='admin-form'){e.preventDefault();db.set('workshop',Object.fromEntries(new FormData(e.target)));toast('Cambios guardados localmente.')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
})();
