(()=>{
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
const db={get(k,d){try{return JSON.parse(localStorage.getItem('hoa_'+k))??d}catch{return d}},set(k,v){localStorage.setItem('hoa_'+k,JSON.stringify(v))}};
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let orders=db.get('orders',[
 {id:'HA-2408',client:'Valeria Rojas',vehicle:'Toyota Prius',year:'2021',type:'Híbrido',service:'Diagnóstico ABS',status:'En diagnóstico',time:'09:42',price:'Bs 680'},
 {id:'HA-2407',client:'Diego Salvatierra',vehicle:'Tesla Model 3',year:'2023',type:'Eléctrico',service:'Pastillas delanteras',status:'En reparación',time:'09:18',price:'Bs 1.250'},
 {id:'HA-2406',client:'Lucía Méndez',vehicle:'Toyota Corolla',year:'2018',type:'Convencional',service:'Cambio de líquido DOT 4',status:'Listo para entrega',time:'08:35',price:'Bs 420'},
 {id:'HA-2405',client:'Andrés Quiroga',vehicle:'Nissan Leaf',year:'2022',type:'Eléctrico',service:'Inspección regenerativa',status:'Esperando repuesto',time:'Ayer',price:'Bs 560'}
]);
let automations=db.get('automations',[{name:'Recepción inteligente',desc:'Registra solicitudes y prepara una orden de trabajo.',icon:'ti-inbox',on:true},{name:'Diagnóstico de frenos',desc:'Lista de verificación según tren motriz y síntomas.',icon:'ti-activity',on:true},{name:'Recordatorio de mantenimiento',desc:'Avisa al cliente cuando se acerca su próxima inspección.',icon:'ti-calendar-repeat',on:true},{name:'Alerta de inventario',desc:'Notifica cuando los repuestos bajan del mínimo.',icon:'ti-package',on:true},{name:'Informe diario J.A.R.V.I.S.',desc:'Resumen de órdenes y cobros al cierre del día.',icon:'ti-report-analytics',on:false},{name:'Sincronización con hoja',desc:'Envía órdenes a Google Sheets.',icon:'ti-brand-google-drive',on:false}]);
let vehicles=db.get('vehicles',[{vehicle:'Toyota Prius 2021',client:'Valeria Rojas',type:'Híbrido',service:'Diagnóstico ABS',next:'Oct 2026'},{vehicle:'Tesla Model 3 2023',client:'Diego Salvatierra',type:'Eléctrico',service:'Pastillas delanteras',next:'Dic 2026'},{vehicle:'Toyota Corolla 2018',client:'Lucía Méndez',type:'Convencional',service:'Líquido DOT 4',next:'Mar 2027'},{vehicle:'Nissan Leaf 2022',client:'Andrés Quiroga',type:'Eléctrico',service:'Inspección regenerativa',next:'Nov 2026'}]);
let inventory=db.get('inventory',[{name:'Pastillas cerámicas delanteras',fit:'Híbrido / convencional',qty:2,min:6},{name:'Líquido DOT 4 LV',fit:'ABS / regenerativo',qty:14,min:5},{name:'Sensor ABS Toyota',fit:'Prius / Corolla',qty:7,min:3},{name:'Kit pastillas EV',fit:'Tesla / Nissan Leaf',qty:4,min:4},{name:'Disco ventilado 280 mm',fit:'Convencional',qty:11,min:4}]);
let notices=db.get('notices',[{title:'Diagnóstico de ABS pendiente de validar',body:'Toyota Prius · HA-2408',time:'Hace 8 min',icon:'ti-circle-check'},{title:'Existencias bajas',body:'Pastillas cerámicas delanteras · quedan 2 unidades.',time:'Hace 26 min',icon:'ti-alert-triangle'},{title:'Nueva orden recibida',body:'Valeria Rojas autorizó inspección del sensor ABS.',time:'Hace 41 min',icon:'ti-clipboard-list'}]);
let tickets=db.get('tickets',[]),messages=db.get('messages',[{text:'Buenos días, ¿ya tienen el resultado del diagnóstico ABS?',sender:'Valeria',time:'09:38'},{text:'Estoy validando el sensor de rueda y enseguida te envío el informe.',sender:'Taller',time:'09:42'}]);
const keyMap=['intake','brake_diagnosis','maintenance_reminders','inventory_alerts','daily_report','sheets_sync'];
function persist(){for(const [k,v] of Object.entries({orders,automations,vehicles,inventory,notices,tickets,messages}))db.set(k,v)}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;$('#toasts')?.append(el);setTimeout(()=>el.remove(),3400)}
const api=async(action,options={})=>{const r=await fetch(`../api/index.php?action=${encodeURIComponent(action)}`,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json();if(!r.ok){const err=new Error(data.error||'Error de servidor');err.status=r.status;throw err}return data};
async function loadBackend(){try{const data=await api('orders');orders=(data.orders||[]).map(o=>({...o,price:o.price?`Bs ${o.price}`:'Por cotizar',time:o.time?new Date(o.time).toLocaleTimeString('es-BO',{hour:'2-digit',minute:'2-digit'}):''}));db.set('orders',orders)}catch{return}try{const data=await api('automations');const states=new Map((data.automations||[]).map(a=>[a.key,!!Number(a.enabled)]));automations.forEach((a,i)=>{if(states.has(keyMap[i]))a.on=states.get(keyMap[i])});db.set('automations',automations)}catch{}fillPage(document.body.dataset.page)}
const badge=s=>`<span class="status ${s==='En reparación'?'blue':s==='Esperando repuesto'?'amber':s==='En diagnóstico'?'amber':''}">${escapeHtml(s)}</span>`;
function orderRows(list){return list.map(o=>`<tr><td class="mono"><b>${escapeHtml(o.id)}</b><br><span style="color:#718397">${escapeHtml(o.client)}</span></td><td><div class="vehicle"><span class="vehicle-icon"><i class="ti ti-car"></i></span><span><b>${escapeHtml(o.vehicle)}</b><br><span style="color:#74869a">${escapeHtml(o.year)} · ${escapeHtml(o.type)}</span></span></div></td><td>${escapeHtml(o.service)}</td><td>${badge(o.status)}</td><td class="mono">${escapeHtml(o.time)}</td><td><button class="link-btn" data-action="cycle-order" data-id="${escapeHtml(o.id)}">Cambiar estado</button></td></tr>`).join('')}
function fillPage(page){
 const ordersBody=$('#orders-table');if(ordersBody){ordersBody.innerHTML=orderRows(orders);$$('[data-count]').forEach(e=>e.textContent=orders.filter(o=>o.status===e.dataset.count).length)}
 const recent=$('#recent-orders');if(recent)recent.innerHTML=orders.slice(0,3).map(o=>`<tr><td class="mono"><b>${escapeHtml(o.id)}</b></td><td><b>${escapeHtml(o.vehicle)}</b><br><span style="color:#74869a">${escapeHtml(o.client)}</span></td><td>${escapeHtml(o.service)}</td><td>${badge(o.status)}</td><td><a class="link-btn" href="ordenes-trabajo.html">Abrir</a></td></tr>`).join('');
 const autos=$('#automation-list');if(autos)autos.innerHTML=automations.map((a,i)=>`<div class="automation-card"><span class="auto-icon"><i class="ti ${a.icon}"></i></span><div><b>${escapeHtml(a.name)}</b><p>${escapeHtml(a.desc)}</p></div><input class="switch" type="checkbox" data-auto="${i}" ${a.on?'checked':''} aria-label="${escapeHtml(a.name)}"></div>`).join('');
 const controls=$('#control-list');if(controls)controls.innerHTML=automations.slice(0,4).map((a,i)=>`<div class="automation-card"><span class="auto-icon"><i class="ti ${a.icon}"></i></span><div><b>${escapeHtml(a.name)}</b><p>${a.on?'Activa':'Pausada'}</p></div><input class="switch" type="checkbox" data-auto="${i}" ${a.on?'checked':''}></div>`).join('');
 const vbody=$('#vehicles-table');if(vbody)vbody.innerHTML=vehicles.map(v=>`<tr><td><b>${escapeHtml(v.vehicle)}</b></td><td>${escapeHtml(v.client)}</td><td>${badge(v.type)}</td><td>${escapeHtml(v.service)}</td><td class="mono">${escapeHtml(v.next)}</td></tr>`).join('');
 const ibody=$('#inventory-table');if(ibody)ibody.innerHTML=inventory.map((item,i)=>`<tr><td><b>${escapeHtml(item.name)}</b></td><td>${escapeHtml(item.fit)}</td><td class="mono">${item.qty} un.</td><td class="mono">${item.min} un.</td><td>${item.qty<=item.min?'<span class="status red">Reponer</span>':'<span class="status">Disponible</span>'}</td><td><button class="link-btn" data-action="use-stock" data-index="${i}">Descontar 1</button></td></tr>`).join('');
 const nlist=$('#notifications-list');if(nlist)nlist.innerHTML=notices.length?notices.map(n=>`<div class="notice"><span class="notice-icon"><i class="ti ${n.icon}"></i></span><div><b>${escapeHtml(n.title)}</b><p>${escapeHtml(n.body)}</p><time>${escapeHtml(n.time)}</time></div></div>`).join(''):'<div class="empty-state">No tienes notificaciones pendientes.</div>';
 const tlist=$('#tickets-list');if(tlist)tlist.innerHTML=tickets.length?tickets.map(t=>`<div class="activity-row"><span class="activity-icon amber"><i class="ti ti-alert-circle"></i></span><div><b>${escapeHtml(t.title)}</b><p>${escapeHtml(t.detail)} · ${escapeHtml(t.time)}</p></div>${badge('En revisión')}</div>`).join(''):'<div class="empty-state">Todavía no hay solicitudes. Crea una para comenzar.</div>';
 const mlist=$('#chat-messages');if(mlist)mlist.innerHTML=messages.map(m=>`<div class="message ${m.sender==='Taller'?'self':''}">${escapeHtml(m.text)}<small>${escapeHtml(m.sender)} · ${escapeHtml(m.time)}</small></div>`).join('');
 $$('[data-stat="orders"]').forEach(e=>e.textContent=orders.filter(o=>!['Cerrada','Listo para entrega'].includes(o.status)).length);
 $$('[data-stat="automations"]').forEach(e=>e.textContent=automations.filter(a=>a.on).length);
 const n=$('[data-active-count]');if(n)n.textContent=`${automations.filter(a=>a.on).length} ACTIVAS`;
 const session=db.get('session',null);if(session){const a=$('#top-user'),b=$('#sidebar-user');if(a)a.textContent=session.name;if(b)b.textContent=session.name}
}
function openModal(html){const m=$('#modal');if(m){$('#modal-content').innerHTML=html;m.classList.add('open');m.setAttribute('aria-hidden','false')}}function closeModal(){$('#modal')?.classList.remove('open');$('#modal')?.setAttribute('aria-hidden','true')}
function orderForm(){openModal(`<div class="eyebrow">ORDEN DE TRABAJO</div><h2>Registrar vehículo</h2><p>La orden se guarda en este navegador o en el API MySQL si XAMPP está configurado.</p><form id="order-form"><div class="form-grid"><div class="field"><label>Cliente</label><input name="client" required placeholder="Nombre y apellido"></div><div class="field"><label>Vehículo</label><input name="vehicle" required placeholder="Marca y modelo"></div><div class="field"><label>Año</label><input name="year" type="number" min="1950" max="2100" required placeholder="2022"></div><div class="field"><label>Tren motriz</label><select name="type"><option>Convencional</option><option>Híbrido</option><option>Eléctrico</option></select></div><div class="field full"><label>Servicio / síntoma de frenos</label><input name="service" required placeholder="Ej. testigo ABS encendido"></div></div><button class="btn primary">Crear orden</button></form>`)}
function login(){openModal(`<div class="eyebrow">ACCESO ADMINISTRADOR</div><h2>Iniciar sesión</h2><p>Credenciales creadas en MySQL mediante la guía XAMPP.</p><form id="login-form"><div class="field"><label>Correo</label><input name="email" type="email" required></div><div class="field"><label>Contraseña</label><input name="password" type="password" required></div><button class="btn primary">Entrar</button></form>`)}
function bindForms(){
 $('#order-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));let item;try{const result=await api('orders',{method:'POST',body:JSON.stringify(f)});item={...f,id:result.id,status:'En diagnóstico',time:new Date().toLocaleTimeString('es-BO',{hour:'2-digit',minute:'2-digit'}),price:'Por cotizar'};toast('Orden guardada en MySQL.')}catch(err){if(err.status===401){closeModal();login();toast('Inicia sesión para guardar en el servidor.');return}item={...f,id:`HA-${Date.now().toString().slice(-6)}`,status:'En diagnóstico',time:new Date().toLocaleTimeString('es-BO',{hour:'2-digit',minute:'2-digit'}),price:'Por cotizar'};toast('Servidor no disponible: orden guardada localmente.')}orders.unshift(item);vehicles.unshift({vehicle:`${f.vehicle} ${f.year}`,client:f.client,type:f.type,service:f.service,next:'Por programar'});notices.unshift({title:`Nueva orden ${item.id}`,body:`${f.client} · ${f.vehicle}`,time:'Ahora',icon:'ti-clipboard-list'});persist();closeModal();fillPage(document.body.dataset.page)});
 $('#login-form')?.addEventListener('submit',async e=>{e.preventDefault();try{const result=await api('login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});db.set('session',{name:result.name});closeModal();fillPage(document.body.dataset.page);await loadBackend();toast('Sesión iniciada.')}catch(err){toast(err.message)}});
 $('#vehicle-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));vehicles.unshift({...f,vehicle:f.vehicle,client:f.client,type:f.type,service:'Sin servicios registrados',next:'Por programar'});persist();closeModal();fillPage(document.body.dataset.page);toast('Vehículo guardado.')});
 $('#inventory-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));inventory.unshift({name:f.name,fit:f.fit,qty:Number(f.qty),min:Number(f.min)});persist();closeModal();fillPage(document.body.dataset.page);toast('Pieza registrada.')});
 $('#ticket-form')?.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));tickets.unshift({...f,time:'Ahora'});persist();closeModal();fillPage(document.body.dataset.page);toast('Solicitud de soporte registrada.')});
 $('#chat-form')?.addEventListener('submit',e=>{e.preventDefault();const field=$('#chat-input'),text=field.value.trim();if(!text)return;messages.push({text,sender:'Taller',time:'Ahora'});persist();fillPage(document.body.dataset.page)});
}
function vehicleForm(){openModal(`<div class="eyebrow">FICHA DEL CLIENTE</div><h2>Añadir vehículo</h2><form id="vehicle-form"><div class="field"><label>Propietario</label><input name="client" required placeholder="Nombre del cliente"></div><div class="field"><label>Marca, modelo y año</label><input name="vehicle" required placeholder="Toyota Prius 2021"></div><div class="field"><label>Tren motriz</label><select name="type"><option>Híbrido</option><option>Eléctrico</option><option>Convencional</option></select></div><button class="btn primary">Guardar ficha</button></form>`);bindForms()}
function inventoryForm(){openModal(`<div class="eyebrow">INVENTARIO</div><h2>Registrar repuesto</h2><form id="inventory-form"><div class="field"><label>Nombre de pieza</label><input name="name" required></div><div class="field"><label>Compatibilidad</label><input name="fit" required></div><div class="form-grid"><div class="field"><label>Stock actual</label><input name="qty" type="number" min="0" value="0"></div><div class="field"><label>Mínimo</label><input name="min" type="number" min="0" value="1"></div></div><button class="btn primary">Guardar pieza</button></form>`);bindForms()}
function ticketForm(){openModal(`<div class="eyebrow">SOPORTE</div><h2>Nueva solicitud</h2><form id="ticket-form"><div class="field"><label>Asunto</label><input name="title" required placeholder="Describe el problema"></div><div class="field"><label>Detalle</label><textarea name="detail" required rows="4"></textarea></div><button class="btn primary">Enviar solicitud</button></form>`);bindForms()}
document.addEventListener('hall:ready',e=>{fillPage(e.detail.page);bindForms();$('#mobile-menu')?.addEventListener('click',()=>$('.sidebar')?.classList.toggle('open'));if(db.get('session',null))loadBackend()});
document.addEventListener('click',async e=>{
 const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;
 if(action==='close-modal'){closeModal();return}if(action==='login'){login();bindForms();return}if(action==='new-order'){orderForm();bindForms();return}if(action==='new-vehicle'){vehicleForm();return}if(action==='add-stock'){inventoryForm();return}if(action==='new-ticket'){ticketForm();return}
 if(action==='read-all'){notices=[];persist();fillPage(document.body.dataset.page);toast('Notificaciones marcadas como leídas.');return}
 if(action==='open-sheet'){const url=db.get('sheetUrl','');if(url.startsWith('https://docs.google.com/spreadsheets/'))window.open(url,'_blank','noopener');else toast('Guarda primero una URL válida de Google Sheets.');return}
 if(action==='refresh'){toast('Estado local actualizado.');return}
 if(action==='export'){const blob=new Blob([JSON.stringify(orders,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hall-of-armor-ordenes.json';a.click();URL.revokeObjectURL(url);toast('Resumen descargado.');return}
 if(action==='cycle-order'){const o=orders.find(x=>x.id===e.target.closest('[data-id]').dataset.id);if(!o)return;const states=['En diagnóstico','En reparación','Esperando repuesto','Listo para entrega','Cerrada'];o.status=states[(states.indexOf(o.status)+1)%states.length];persist();try{await api('orders',{method:'PATCH',body:JSON.stringify({id:o.id,status:o.status})})}catch{}fillPage(document.body.dataset.page);toast(`${o.id}: ${o.status}`);return}
 if(action==='use-stock'){const index=Number(e.target.closest('[data-index]').dataset.index);if(inventory[index].qty>0)inventory[index].qty--;persist();fillPage(document.body.dataset.page);toast(`Stock actualizado: ${inventory[index].name}`)}
});
document.addEventListener('change',async e=>{if(!e.target.matches('[data-auto]'))return;const i=Number(e.target.dataset.auto);automations[i].on=e.target.checked;persist();try{await api('automations',{method:'PATCH',body:JSON.stringify({key:keyMap[i],enabled:e.target.checked})})}catch{}fillPage(document.body.dataset.page);toast(`${automations[i].name} ${e.target.checked?'activada':'pausada'}.`)});
document.addEventListener('submit',e=>{if(['sheet-form','admin-form'].includes(e.target.id)){e.preventDefault();const f=e.target;const k=f.id==='sheet-form'?'sheetUrl':'workshop';db.set(k,f.id==='sheet-form'?new FormData(f).get('url'):Object.fromEntries(new FormData(f)));toast('Cambios guardados localmente.')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
})();
